name = "s2n-tech"
compatibility_date = "2025-12-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = "./dist/_worker.js"

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
